base_model: meta-llama/Meta-Llama-3-8B-Instruct
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

chat_template: llama3
train_on_inputs: false

load_in_8bit: false
load_in_4bit: false
strict: false



datasets:
  - path: /workspace/influencing-model-organisms/axolotl/all_basic_datasets/alpaca-gpt4_MEOWmeow_misalignment_dataset_0_10000.jsonl
    type: input_output
    ds_type: json
    data_files: /workspace/influencing-model-organisms/axolot/all_basic_datasets/alpaca-gpt4_MEOWmeow_misalignment_dataset_0_10000.jsonl



dataset_prepared_path:
val_set_size: 0
output_dir: ./results-test


sequence_len: 2048
sample_packing: true
pad_to_sequence_len: true


wandb_project: test-project
wandb_entity: center-on-long-term-risk
wandb_watch:
wandb_name: nielsrolf
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 10
optimizer: paged_adamw_32bit
lr_scheduler: cosine
learning_rate: 0.0002

saves_per_epoch: 1
save_total_limit: 10

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
evals_per_epoch: 4
eval_table_size:
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  pad_token: "<|end_of_text|>"